# Site settings
title: Gepeszed.hu
email: gepeszed@gamil.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

facebook_username: gépészed.hu
instagram_username:

# Build settings
markdown: kramdown
